### ISSUE TITLE
Error running evaluation command

### ISSUE THREAD

**Issue by tomhosking** [megagonlabs/coop#4]
Hi,

The evaluation command provided in the readme doesn't quite work:
```
> python coop.search.py log/bimeanvae/space
python3: can't open file 'coop.search.py': [Errno 2] No such file or directory
```

Trying a few other variants also doesn't work:
```
> python -m coop.search.py log/bimeanvae/space
Traceback (most recent call last):
  File "/home/tom/miniconda3/envs/coop/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/tom/miniconda3/envs/coop/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/mnt/ext/phd/external/opagg/coop/coop/search.py", line 14, in <module>
    from models import Model
ImportError: cannot import name 'Model' from 'models' (unknown location)
```

```
> python coop/search.py log/bimeanvae/space
Traceback (most recent call last):
  File "coop/search.py", line 15, in <module>
    from reader import ReviewTest, OptimusTest
  File "/mnt/ext/phd/external/opagg/coop/coop/reader.py", line 10, in <module>
    from .tokenizer import Tokenizer
ImportError: attempted relative import with no known parent package
```

What's the correct way to run the evaluation script?

Thanks!

**Comment by isomap** [comment]
Hi Tom,

If I remember correctly, this script should work correctly if you clone this repo and run it under the root directory of this repo. So please make sure where to run this script.

Thanks!
